### ISSUE TITLE
请教一下classmap相关问题

### ISSUE THREAD

**Issue by pengxuxu** [limingxinleo/easywechat-classmap#2]
#### 李大佬请教一下:
1. 在包的使用说明中“EasyWeChat 6.x 使用的是 Symfony Http Client，在常驻内存的服务中使用时，HttpClient 会因为多个协程共用，而报错。”这句描述是不是按swoole官方编程须知里 [“在多个协程中共用一个连接”](https://wiki.swoole.com/#/coroutine/notice?id=%e5%9c%a8%e5%a4%9a%e4%b8%aa%e5%8d%8f%e7%a8%8b%e9%97%b4%e5%85%b1%e7%94%a8%e4%b8%80%e4%b8%aa%e8%bf%9e%e6%8e%a5 ) 这样来理解？ 

2. easywecat4和5使用的是guzzle，看hyperf的官方文档中，只是替换了其中的handler，如果使用了 Swoole 4.7.0 及以上版本，并且开启了 native curl 选项，则可以不用替换，这里也没有用hyperf的classmap替换easywechat中的http_client，而为什么到6版本就需要用classmap替换其中的HttpClient呢？还请大佬多多指教！！！
```php
    protected function client(): HttpClientInterface
    {
        return Context::getOrSet(static::class, function () {
            return SymfonyClient::create(RequestUtil::formatDefaultOptions($this->option));
        });
    }
```

**Comment by limingxinleo** [comment]
第一点，是的。

第二点，之前的版本我们替换了 handler，所以实际上你请求接口时，每次都会在同一个 handler 里实例化不同的 client，所以不会出现问题。

而新版本没有走替换 handler 的方式，直接处理了拿 Client 的逻辑，效果是一致的。

**Comment by pengxuxu** [comment]
好的，谢谢你的回复，hyperf会越来越好的。
